### ISSUE TITLE
Tracking issue for dashboard design iteration 3

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#108]
```[tasklist]
### High Priority
- [ ] https://github.com/Lodestone-Team/lodestone/issues/132
- [ ] https://github.com/Lodestone-Team/lodestone/issues/133
```

```[tasklist]
### Lower Priority
- [ ] https://github.com/Lodestone-Team/lodestone/issues/134
- [ ] https://github.com/Lodestone-Team/lodestone/issues/137
- [ ] Sync settings left nav to dashboard left nav (style change + move user login)
```

```[tasklist]
### Nice to haves
- [ ] https://github.com/Lodestone-Team/lodestone/issues/104
- [ ] https://github.com/Lodestone-Team/lodestone/issues/136
- [ ] https://github.com/Lodestone-Team/lodestone/issues/149
```

![image](https://user-images.githubusercontent.com/47200772/212567732-b9383124-2285-4bf9-8e68-bc9ed3672b02.png)

**Comment by Ynng** [comment]
Current situation

TODO:
- New "pill" button
- Remove "tabs", implement the left nav navigation buttons
- Move user login to left nav

![image](https://user-images.githubusercontent.com/44907675/212568245-56d325dc-df44-4075-ad60-b4bc690adf6f.png)

**Comment by Arcslogger** [comment]
- add restart button and minecraft version

**Comment by Ynng** [comment]
We'll close this for now, since the majority is done, and the rest (new setup modal, new pages) are too miscellaneous.
